from pathlib import Path
BASE_DIR=Path(__file__).resolve().parents[1]
RAW_DIR=BASE_DIR/'data'/'raw'; PROCESSED_DIR=BASE_DIR/'data'/'processed'
BRANDS={'ELEBAR':{'label':'Elebar','colors':['#FBBA00','#571744','#6B4B63']},'BLU':{'label':'Punto Blu','colors':['#0760f7','#024099','#FBBA00']}}
CANONICAL_COLUMNS=['brand','platform','account','account_id','username','post_id','published_datetime','date','time','url','title','copy','format','content_type','video_duration_seconds','reach','impressions','video_views','likes','comments','shares','saves','clicks','followers','followers_gained','followers_lost','interactions','er_reach','er_impressions','source_file','source_row','_record_key']
FORMAT_MAP={'fotos':'Imagen','foto':'Imagen','imagenes':'Imagen','imagen':'Imagen','vídeos':'Video','videos':'Video','vídeo':'Video','video':'Video','secuencia de instagram':'Carrusel','carrusel':'Carrusel','carousel':'Carrusel','reel de instagram':'Reel','reel':'Reel','post':'Post'}
PLATFORM_MAP={'facebook':'Facebook','instagram':'Instagram','fb':'Facebook','ig':'Instagram'}
NUMERIC_COLUMNS=['video_duration_seconds','reach','impressions','video_views','likes','comments','shares','saves','clicks','followers','followers_gained','followers_lost','interactions']
ALIASES={'post_id':['identificador de la publicación'],'account_id':['identificador de la página','identificador de la cuenta'],'account':['nombre de la página','nombre de la cuenta'],'username':['nombre de usuario de la cuenta'],'title':['título'],'copy':['descripción'],'published_datetime':['hora de publicación'],'url':['enlace permanente'],'format':['tipo de publicación'],'video_duration_seconds':['duración (segundos)'],'video_views':['visualizaciones'],'reach':['alcance'],'likes':['reacciones','me gusta'],'comments':['comentarios'],'shares':['veces que se ha compartido'],'saves':['veces guardado'],'clicks':['total de clics'],'followers':['seguidores'],'interactions':['reacciones, comentarios y veces que se ha compartido'],'impressions':['impresiones']}
